### ISSUE TITLE
duncan@duncanhunter.com.au

### ISSUE THREAD

**Issue by duncanhunter** [cfsamson/HotTowelTypescript#1]
The nuget package was causing errors?

For those using VS2013 with update 3 to make it work I followed three steps:
1. I removed the references in the image below in the package references in my webapi proj
2. Installed the nuget package
3. I updated all packages in nuget
![image](https://cloud.githubusercontent.com/assets/2058227/4022303/cfee3838-2b29-11e4-9a00-6d09042aeab1.png)

**Comment by cfsamson** [comment]
Thanks, I'll have a look at this. Haven't experienced this in VS2013 update 2. Based on the references above It seems to relate to the breeze.server.webapi2 package. I'll try to replecate this issue in vs2013 update 3 and see if updating the breeze.server.webapi2 package to version 1.4.17 fixes it.

**Comment by duncanhunter** [comment]
Thank you!!!!!!!!! for the typescript version. I have a project in hot towel and looking to apply typescript to access using it more so this helped!

**Comment by cfsamson** [comment]
Cool, thanks for the feedback :)
