### ISSUE TITLE
No breeze usage

### ISSUE THREAD

**Issue by nzmedet** [cfsamson/HotTowelTypescript#3]
You made just implementation, but it wouldn't work, cuz you didn't even provide dataService url, this is just a mock which wont work on real sample with odata backend (no $metadata consumption logic), sadly this project template is useless

**Comment by MikaereC-zz** [comment]
Wrong, this template is great !  It is a replica of John Papa's HotTowel, which does not come with breeze.  You need to get a PluralSight subscription and complete his course http://www.pluralsight.com/courses/build-apps-angular-breeze in which he shows you, step by step, how to include breeze etc.  

I recommend purchasing the pro licence so you get the source code too.

**Comment by cfsamson** [comment]
MikaereC is right, this is just a template to get started on a nice path. Not an example. You need to create a breeze controller yourself and handle the server side part of it, but it is [quite easy!](http://www.getbreezenow.com/samples/breeze-web-api-odata)

The template is intentionally lightweight and does not add more than needed but sets up a lot of the plumbing you usually need anyway.

To use it for learning purposes I reccomend John Papas course which MikaereC linked to.

**Comment by nzmedet** [comment]
Checkout http://stackoverflow.com/questions/29058810/is-there-any-angularjs-asp-net-webapi-odata-breeze-js-typescript-example/29066931#29066931
