### ISSUE TITLE
Bootstrap dialog does not seem to register

### ISSUE THREAD

**Issue by MikaereC-zz** [cfsamson/HotTowelTypescript#4]
Hi,

Thanks for creating this nuget package, it's been great to use TypeScript with HotTowel.

However, when I attempt to use the bootstrap dialog (in app\common\bootstrap.dialog.ts) using the same syntax that John Papa users (injected as 'bootstrap.dialog' into the controller's constructor), I get a provider exception.

Any ideas ?

**Comment by cfsamson** [comment]
Hmm, I'll have a look at this and get back to you soon!

Carl Fredrik Samson

**Comment by cfsamson** [comment]
Thanks for pointing this out. I have made some errors in "bootstrap.dialog.ts", the error beeing that I actually haven't registered the service with angular :)

The quick fix to make it work is to change the last lines of bootstrap.dialog.ts with this:

```
    // Create the common.bootstrap module angular
   var bootstrapModule = angular.module(BootstrapDialog.serviceId, ['ui.bootstrap']);

   // Register bootstrap.dialog service
   bootstrapModule.factory('bootstrap.dialog', ['$modal', '$templateCache', 
           (m, tc) => new BootstrapDialog(m, tc)])
```

So the end of that file should look like this:

![image](https://cloud.githubusercontent.com/assets/8337848/6678062/29a9bf98-cc36-11e4-8a08-968357015044.png)

Now you can use it as you do in the original example.

The real fix is not that big but I shouldn't have named

```
  class BootstrapDialog implements IBootstrapDialog
  {
       public static serviceId: string = 'common.bootstrap';
       ....
```

That should be called "bootstrap.dialog" and then to be consistent I should create the module "common.bootstrap" in a seperate file. I will make an update and fix this, but the fix provided above is really easy and fixes everything.

**Comment by cfsamson** [comment]
OK, I have now updated the nuget package with a more permanent fix. Just to give a full answer to this I'll show you the code I used to display the modal. I added a button in dashboard.html and set the data-ng-click = "vm.showmodal()"

You can then use the returned promise from this.modal.confirmationDialog to check what the response was so now everything should work as espected.

```
   export class DashboardCtrl
{
    public static controllerId: string = 'dashboardCtrl';
   //#region Variables
    controllerId = DashboardCtrl.controllerId;
    common: App.Shared.ICommon;
    datacontext: App.Services.IDatacontext;
    log: any;
    messageCount: number;
    news: INews;
    people: Array<any> = [];
    private modal: any;

    //#endregion
    constructor(common, datacontext, modal)
    {
        this.common = common;
        this.datacontext = datacontext;
        this.log = common.logger.getLogFn();
        this.news = this.getNews();
        this.modal = modal;

        // Queue all promises and wait for them to finish before loading the view
        this.activate([this.getMessageCount(), this.getPeople()]);
    }

    // TODO: is there a more elegant way of activating the controller - base class?
    activate(promises: Array<ng.IPromise<any>>)
    {
        this.common.activateController(promises, this.controllerId)
            .then(() => { this.log('Activated Dashboard View'); });
    }

    //#region Public Methods
    getNews(): INews
    {
        return {
            title: "Hot Towel Typescript",
            description: 'Hot Towel Typescript is a SPA template using Angular, Breeze and Typescript. '
                + 'This is a conversion of John Papas HotTowel.Angular.Breeze package'
        };
    }

    getMessageCount()
    {
        return this.datacontext.getMessageCount().then(data =>
        {
            return this.messageCount = data;
        });
    }

    getPeople()
    {
        return this.datacontext.getPeople().then(data =>
        {
            return this.people = data;
        });
    }

    showmodal()
    {
        this.modal.confirmationDialog('Shure', 'Are you really shure?');
    }

    //#endregion
 }

// register controller with angular
app.controller(DashboardCtrl.controllerId, ['common', 'datacontext', 'bootstrap.dialog',
    (c, dc, bd) => new App.Controllers.DashboardCtrl(c, dc, bd)
]);
```

**Comment by MikaereC-zz** [comment]
That works great !  Thanks for the speedy resolution :)
